apiVersion: v1
kind: Pod
metadata:
  name: sample-env-fail
  labels:
    app: sample-app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    command: ["echo"]
    args: ["${TESTENV}", "${HOSTNAME}"]
    # Only env variables defined inside the pod manifest can be loaded in the form of $(TESTENV).
    env:
    - name: TESTENV
      value: "100"

# dev@DESKTOP-GCJUTAU:~/git/k8s-playground/ch7$ kubectl logs sample-env-fail
# ${TESTENV} ${HOSTNAME}
