apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-immutable
type: Opaque
data:
  username: cm9vdA== # root
  password: cm9vdHBhc3N3v3Jk # rootpassword
# 
immutable: true # immutable!
# 1. Prevent unexpected changes
# 2. Cannot be changed using "kubectl patch", "kubectl apply".
# 3. No need to keep an eye on resource changes, which improves performance
# 4. Cannot change "immutable value" to "true" during execution.
