apiVersion: v1
kind: Pod
metadata:
  name: sample-downward-api
spec:
  containers:
  - name: nginx-container
    image: nginx:1.15
    volumeMounts:
    - name: downward-api-volume
      mountPath: /srv
  volumes:
  - name: downward-api-volume
    # Downward API is a mechanism in Kubernetes that passes information about resources (Pod, container, node, etc.) into the container.
    downwardAPI:
      items:
      - path: "podname"
        fieldRef:
          fieldPath: metadata.name
      - path: "cpu-request"
        resourceFieldRef:
          containerName: nginx-container
          resource: requests.cpu
