apiVersion: v1
kind: Pod
metadata:
  name: sample-emptydir
spec:
  containers:
  - image  : nginx:1.16
    name: nginx-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    # Temporary volume. When a pod terminates, it is deleted.
    emptyDir: {}
