apiVersion: v1
kind: Service
metadata:
  name: sample-lb
  # nodePort and externalIP are single points of failure because they communicate with a single assigned IP address.
spec:
  # When you create a LoadBalancer in GKE, a GCLB is created.
  type: LoadBalancer
  # In the case of GKE, users can't use virtual IPs arbitrarily
  # loadBalancerIP: xxx.xxx.xxx.xxx
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 80
    nodePort: 30082
  selector:
    app: samplpe-app
  # Setting a connection limit. it works by iptables on the K8S node.
  loadBalancerSourceRanges:
  - 10.0.0.0/8
