apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-2pod
  template:
    metadata:
      labels:
        app: sample-2pod
    spec:
      containers:
         - name: nginx-container
           image: nginx:1.16

